// Demo data for MediFind frontend development
// This is clearly marked as DEMO DATA - not real pharmacy or availability data

export const DEMO_MEDICINES = [
  {
    id: 1,
    name: 'Paracetamol',
    genericName: 'Acetaminophen',
    category: 'Analgesic / Antipyretic',
    manufacturer: 'GSK Pharmaceuticals',
    strength: '500mg',
    dosageForm: 'Tablet',
    description: 'Used for temporary relief of mild to moderate pain and fever.',
    pharmaciesCount: 14,
    availableCount: 10,
    lowStockCount: 2,
    outOfStockCount: 2,
    imageUrl: null,
  },
  {
    id: 2,
    name: 'Amoxicillin',
    genericName: 'Amoxicillin Trihydrate',
    category: 'Antibiotic',
    manufacturer: 'Cipla Ltd.',
    strength: '250mg',
    dosageForm: 'Capsule',
    description: 'Broad-spectrum antibiotic for bacterial infections.',
    pharmaciesCount: 9,
    availableCount: 6,
    lowStockCount: 2,
    outOfStockCount: 1,
    imageUrl: null,
  },
  {
    id: 3,
    name: 'Cetirizine',
    genericName: 'Cetirizine Hydrochloride',
    category: 'Antihistamine',
    manufacturer: 'Sun Pharma',
    strength: '10mg',
    dosageForm: 'Tablet',
    description: 'For relief of allergy symptoms including hay fever.',
    pharmaciesCount: 11,
    availableCount: 8,
    lowStockCount: 3,
    outOfStockCount: 0,
    imageUrl: null,
  },
  {
    id: 4,
    name: 'Azithromycin',
    genericName: 'Azithromycin Dihydrate',
    category: 'Antibiotic',
    manufacturer: 'Pfizer',
    strength: '500mg',
    dosageForm: 'Tablet',
    description: 'Antibiotic for a wide variety of bacterial infections.',
    pharmaciesCount: 7,
    availableCount: 4,
    lowStockCount: 2,
    outOfStockCount: 1,
    imageUrl: null,
  },
  {
    id: 5,
    name: 'Ibuprofen',
    genericName: 'Ibuprofen',
    category: 'NSAID / Anti-inflammatory',
    manufacturer: 'Abbott India',
    strength: '400mg',
    dosageForm: 'Tablet',
    description: 'Anti-inflammatory drug for pain relief and fever.',
    pharmaciesCount: 12,
    availableCount: 9,
    lowStockCount: 1,
    outOfStockCount: 2,
    imageUrl: null,
  },
  {
    id: 6,
    name: 'Metformin',
    genericName: 'Metformin Hydrochloride',
    category: 'Antidiabetic',
    manufacturer: 'USV Ltd.',
    strength: '500mg',
    dosageForm: 'Tablet',
    description: 'First-line medication for type 2 diabetes.',
    pharmaciesCount: 8,
    availableCount: 7,
    lowStockCount: 1,
    outOfStockCount: 0,
    imageUrl: null,
  },
];

export const DEMO_PHARMACIES = [
  {
    id: 1,
    name: 'Apollo Pharmacy — Hitech City',
    brand: 'Apollo Pharmacy',
    verified: true,
    open: true,
    address: 'Plot 14, Mindspace IT Park, Hitech City, Hyderabad, 500081',
    area: 'Hitech City',
    city: 'Hyderabad',
    distance: '0.6 km',
    phone: '+91 40 2311 0021',
    email: 'hitech.apollo@pharmacy.in',
    availableMedicines: 184,
    operatingHours: '24 Hours',
    open24Hours: true,
    opensAt: '00:00',
    closesAt: '23:59',
    rating: 4.8,
    totalReviews: 246,
    verificationStatus: 'APPROVED',
    services: ['24/7 Service', 'Home Delivery', 'Online Consultation'],
    lat: 17.4435,
    lng: 78.3772,
  },
  {
    id: 2,
    name: 'MedPlus — Madhapur',
    brand: 'MedPlus',
    verified: true,
    open: true,
    address: '102, Main Road, Near Metro Pillar C-12, Madhapur, Hyderabad, 500081',
    area: 'Madhapur',
    city: 'Hyderabad',
    distance: '1.2 km',
    phone: '+91 40 2980 4455',
    email: 'madhapur@medplusindia.com',
    availableMedicines: 162,
    operatingHours: '7:30 AM – 11:00 PM',
    open24Hours: false,
    opensAt: '07:30',
    closesAt: '23:00',
    rating: 4.6,
    totalReviews: 188,
    verificationStatus: 'APPROVED',
    services: ['Home Delivery', 'Drive-thru', 'Digital Prescriptions'],
    lat: 17.4483,
    lng: 78.3915,
  },
  {
    id: 3,
    name: 'HealthKart Pharmacy — Gachibowli',
    brand: 'HealthKart',
    verified: true,
    open: true,
    address: 'G-05, DLF Cyber City Road, Gachibowli, Hyderabad, 500032',
    area: 'Gachibowli',
    city: 'Hyderabad',
    distance: '2.4 km',
    phone: '+91 40 4477 8899',
    email: 'gachibowli@healthkart.com',
    availableMedicines: 145,
    operatingHours: '8:00 AM – 10:30 PM',
    open24Hours: false,
    opensAt: '08:00',
    closesAt: '22:30',
    rating: 4.5,
    totalReviews: 142,
    verificationStatus: 'APPROVED',
    services: ['Home Delivery', 'Health Supplements', 'Lab Tests'],
    lat: 17.4401,
    lng: 78.3489,
  },
  {
    id: 4,
    name: 'Guardian Pharmacy — Kondapur',
    brand: 'Guardian',
    verified: true,
    open: false,
    address: 'Shop 12, Botanical Garden Road, Kondapur, Hyderabad, 500084',
    area: 'Kondapur',
    city: 'Hyderabad',
    distance: '3.1 km',
    phone: '+91 40 6622 3311',
    email: 'kondapur@guardianpharmacy.in',
    availableMedicines: 118,
    operatingHours: '9:00 AM – 9:30 PM',
    open24Hours: false,
    opensAt: '09:00',
    closesAt: '21:30',
    rating: 4.4,
    totalReviews: 96,
    verificationStatus: 'APPROVED',
    services: ['Baby Care', 'Personal Care', 'Home Delivery'],
    lat: 17.4612,
    lng: 78.3615,
  },
  {
    id: 5,
    name: 'Wellness Forever — Jubilee Hills',
    brand: 'Wellness Forever',
    verified: true,
    open: true,
    address: 'Road No. 36, Opposite Metro Pillar 1680, Jubilee Hills, Hyderabad, 500033',
    area: 'Jubilee Hills',
    city: 'Hyderabad',
    distance: '3.8 km',
    phone: '+91 40 4852 9000',
    email: 'jubileehills@wellnessforever.in',
    availableMedicines: 210,
    operatingHours: '24 Hours',
    open24Hours: true,
    opensAt: '00:00',
    closesAt: '23:59',
    rating: 4.9,
    totalReviews: 310,
    verificationStatus: 'APPROVED',
    services: ['24/7 Service', 'Home Delivery', 'Emergency Medicines', 'Drive-thru'],
    lat: 17.4319,
    lng: 78.4073,
  },
  {
    id: 6,
    name: 'Frank Ross Pharmacy — Banjara Hills',
    brand: 'Frank Ross',
    verified: true,
    open: true,
    address: 'Road No. 12, Near MLA Colony, Banjara Hills, Hyderabad, 500034',
    area: 'Banjara Hills',
    city: 'Hyderabad',
    distance: '4.9 km',
    phone: '+91 40 2339 7788',
    email: 'banjarahills@frankross.in',
    availableMedicines: 175,
    operatingHours: '8:00 AM – 11:00 PM',
    open24Hours: false,
    opensAt: '08:00',
    closesAt: '23:00',
    rating: 4.7,
    totalReviews: 165,
    verificationStatus: 'APPROVED',
    services: ['Home Delivery', 'Senior Citizen Discount', 'Doctor Teleconsult'],
    lat: 17.4156,
    lng: 78.4350,
  },
  {
    id: 7,
    name: 'Fortis HealthWorld — Begumpet',
    brand: 'Fortis HealthWorld',
    verified: true,
    open: true,
    address: '1-11-252, SP Road, Begumpet, Hyderabad, 500016',
    area: 'Begumpet',
    city: 'Hyderabad',
    distance: '6.2 km',
    phone: '+91 40 6638 1234',
    email: 'begumpet@fortishealthworld.com',
    availableMedicines: 195,
    operatingHours: '24 Hours',
    open24Hours: true,
    opensAt: '00:00',
    closesAt: '23:59',
    rating: 4.8,
    totalReviews: 280,
    verificationStatus: 'APPROVED',
    services: ['24/7 Service', 'Surgical Equipment', 'Speciality Medicines'],
    lat: 17.4447,
    lng: 78.4664,
  },
  {
    id: 8,
    name: 'Netmeds Store — Kukatpally',
    brand: 'Netmeds',
    verified: true,
    open: true,
    address: 'KPHB Colony Phase 3, Main Road, Kukatpally, Hyderabad, 500072',
    area: 'Kukatpally',
    city: 'Hyderabad',
    distance: '5.5 km',
    phone: '+91 40 4012 3456',
    email: 'kukatpally@netmeds.com',
    availableMedicines: 158,
    operatingHours: '8:30 AM – 10:00 PM',
    open24Hours: false,
    opensAt: '08:30',
    closesAt: '22:00',
    rating: 4.5,
    totalReviews: 125,
    verificationStatus: 'APPROVED',
    services: ['Home Delivery', 'Order Pickup', 'Discounts'],
    lat: 17.4938,
    lng: 78.3986,
  },
  {
    id: 9,
    name: 'Aster Pharmacy — Panjagutta',
    brand: 'Aster Pharmacy',
    verified: true,
    open: true,
    address: 'Nagarjuna Circle, Panjagutta, Hyderabad, 500082',
    area: 'Panjagutta',
    city: 'Hyderabad',
    distance: '5.8 km',
    phone: '+91 40 4911 2233',
    email: 'panjagutta@asterpharmacy.in',
    availableMedicines: 168,
    operatingHours: '8:00 AM – 11:00 PM',
    open24Hours: false,
    opensAt: '08:00',
    closesAt: '23:00',
    rating: 4.6,
    totalReviews: 154,
    verificationStatus: 'APPROVED',
    services: ['Home Delivery', 'Prescription Refill', 'Vital Checks'],
    lat: 17.4262,
    lng: 78.4516,
  },
  {
    id: 10,
    name: 'Noble Chemist — Somajiguda',
    brand: 'Noble Chemist',
    verified: true,
    open: false,
    address: 'Raj Bhavan Road, Somajiguda, Hyderabad, 500082',
    area: 'Somajiguda',
    city: 'Hyderabad',
    distance: '6.5 km',
    phone: '+91 40 2340 5566',
    email: 'somajiguda@noblechemist.in',
    availableMedicines: 132,
    operatingHours: '9:00 AM – 9:00 PM',
    open24Hours: false,
    opensAt: '09:00',
    closesAt: '21:00',
    rating: 4.3,
    totalReviews: 89,
    verificationStatus: 'APPROVED',
    services: ['Ayurvedic Medicines', 'Generic Drugs'],
    lat: 17.4230,
    lng: 78.4600,
  },
  {
    id: 11,
    name: 'CityCare 24x7 Pharmacy — Secunderabad',
    brand: 'CityCare',
    verified: true,
    open: true,
    address: '15, Station Road, Near Railway Station, Secunderabad, 500003',
    area: 'Secunderabad',
    city: 'Hyderabad',
    distance: '8.4 km',
    phone: '+91 40 2770 1122',
    email: 'secunderabad@citycare.in',
    availableMedicines: 205,
    operatingHours: '24 Hours',
    open24Hours: true,
    opensAt: '00:00',
    closesAt: '23:59',
    rating: 4.7,
    totalReviews: 295,
    verificationStatus: 'APPROVED',
    services: ['24/7 Service', 'Emergency Oxygen', 'Home Delivery'],
    lat: 17.4399,
    lng: 78.4983,
  },
  {
    id: 12,
    name: 'LifeCare Medicos — Dilsukhnagar',
    brand: 'LifeCare',
    verified: true,
    open: true,
    address: 'Opp. Bus Station, Main Road, Dilsukhnagar, Hyderabad, 500060',
    area: 'Dilsukhnagar',
    city: 'Hyderabad',
    distance: '11.2 km',
    phone: '+91 40 2404 8899',
    email: 'dilsukhnagar@lifecare.in',
    availableMedicines: 140,
    operatingHours: '8:00 AM – 10:30 PM',
    open24Hours: false,
    opensAt: '08:00',
    closesAt: '22:30',
    rating: 4.4,
    totalReviews: 112,
    verificationStatus: 'APPROVED',
    services: ['Home Delivery', 'Medical Supplies'],
    lat: 17.3688,
    lng: 78.5247,
  },
];

export const DEMO_INVENTORY = [
  { id: 1, medicineId: 1, medicineName: 'Paracetamol', genericName: 'Acetaminophen', category: 'Analgesic', quantity: 450, price: 12.50, status: 'AVAILABLE', threshold: 50, lastUpdated: '2026-10-03T08:30:00Z', pharmacyId: 1 },
  { id: 2, medicineId: 2, medicineName: 'Amoxicillin', genericName: 'Amoxicillin Trihydrate', category: 'Antibiotic', quantity: 30, price: 85.00, status: 'LOW_STOCK', threshold: 40, lastUpdated: '2026-10-03T07:15:00Z', pharmacyId: 1 },
  { id: 3, medicineId: 3, medicineName: 'Cetirizine', genericName: 'Cetirizine HCl', category: 'Antihistamine', quantity: 0, price: 35.00, status: 'OUT_OF_STOCK', threshold: 20, lastUpdated: '2026-10-02T18:00:00Z', pharmacyId: 1 },
  { id: 4, medicineId: 4, medicineName: 'Azithromycin', genericName: 'Azithromycin Dihydrate', category: 'Antibiotic', quantity: 120, price: 145.00, status: 'AVAILABLE', threshold: 30, lastUpdated: '2026-10-03T09:00:00Z', pharmacyId: 1 },
  { id: 5, medicineId: 5, medicineName: 'Ibuprofen', genericName: 'Ibuprofen', category: 'NSAID', quantity: 15, price: 28.00, status: 'LOW_STOCK', threshold: 20, lastUpdated: '2026-10-03T06:45:00Z', pharmacyId: 1 },
  { id: 6, medicineId: 6, medicineName: 'Metformin', genericName: 'Metformin HCl', category: 'Antidiabetic', quantity: 200, price: 22.00, status: 'AVAILABLE', threshold: 50, lastUpdated: '2026-10-03T10:00:00Z', pharmacyId: 1 },
];

export const DEMO_SEARCH_HISTORY = [
  { id: 1, query: 'Paracetamol', date: '2026-10-03T09:30:00Z', results: 14 },
  { id: 2, query: 'Azithromycin', date: '2026-10-02T14:15:00Z', results: 7 },
  { id: 3, query: 'Cetirizine 10mg', date: '2026-10-01T11:00:00Z', results: 11 },
  { id: 4, query: 'Ibuprofen 400mg', date: '2026-09-30T16:45:00Z', results: 9 },
];

export const DEMO_ALERTS = [
  { id: 1, medicineName: 'Amoxicillin 250mg', pharmacyName: 'Any Pharmacy', status: 'ACTIVE', type: 'BACK_IN_STOCK', createdAt: '2026-09-28T10:00:00Z', notificationChannel: 'EMAIL' },
  { id: 2, medicineName: 'Cetirizine 10mg', pharmacyName: 'Apollo Pharmacy — Demo Branch', status: 'ACTIVE', type: 'AVAILABILITY_UPDATE', createdAt: '2026-09-25T14:00:00Z', notificationChannel: 'EMAIL' },
];

export const DEMO_NOTIFICATIONS = [
  { id: 1, type: 'BACK_IN_STOCK', title: 'Amoxicillin is back in stock!', message: 'Amoxicillin 250mg is now available at MedPlus — Demo Branch.', read: false, createdAt: '2026-10-03T08:00:00Z' },
  { id: 2, type: 'STOCK_UPDATE', title: 'Stock Update', message: 'Paracetamol stock has been updated at Apollo Pharmacy.', read: false, createdAt: '2026-10-03T07:30:00Z' },
  { id: 3, type: 'SYSTEM', title: 'Welcome to MediFind', message: 'Your account has been successfully created. Start searching for medicines!', read: true, createdAt: '2026-10-01T10:00:00Z' },
];

export const DEMO_PLATFORM_STATS = {
  medicinesListed: 2847,
  verifiedPharmacies: 134,
  activeUsers: 12650,
  availabilityUpdates: 48920,
  isDemoData: true,
};

export const MEDICINE_CATEGORIES = [
  'Analgesic / Antipyretic',
  'Antibiotic',
  'Antihistamine',
  'NSAID / Anti-inflammatory',
  'Antidiabetic',
  'Antihypertensive',
  'Antacid',
  'Antifungal',
  'Antiviral',
  'Vitamin / Supplement',
  'Dermatological',
  'Respiratory',
  'Cardiovascular',
  'Neurological',
  'Gastrointestinal',
  'Ophthalmic',
  'Other',
];

export const DOSAGE_FORMS = [
  'Tablet',
  'Capsule',
  'Syrup',
  'Injection',
  'Cream',
  'Ointment',
  'Drops',
  'Inhaler',
  'Patch',
  'Suppository',
  'Suspension',
  'Powder',
  'Gel',
  'Lotion',
  'Solution',
];

export const POPULAR_SEARCHES = [
  'Paracetamol',
  'Amoxicillin',
  'Cetirizine',
  'Ibuprofen',
  'Azithromycin',
  'Metformin',
  'Omeprazole',
  'Atorvastatin',
];

export const STATUS_COLORS = {
  AVAILABLE: { bg: 'bg-green-50', text: 'text-green-700', ring: 'ring-green-200', dot: 'bg-green-500' },
  LOW_STOCK: { bg: 'bg-amber-50', text: 'text-amber-700', ring: 'ring-amber-200', dot: 'bg-amber-500' },
  OUT_OF_STOCK: { bg: 'bg-red-50', text: 'text-red-700', ring: 'ring-red-200', dot: 'bg-red-500' },
  UNKNOWN: { bg: 'bg-neutral-100', text: 'text-neutral-600', ring: 'ring-neutral-200', dot: 'bg-neutral-400' },
};

export const VERIFICATION_STATUS = {
  APPROVED: { label: 'Verified', color: 'text-primary-700', bg: 'bg-primary-50', ring: 'ring-primary-200' },
  PENDING: { label: 'Pending', color: 'text-amber-700', bg: 'bg-amber-50', ring: 'ring-amber-200' },
  REJECTED: { label: 'Rejected', color: 'text-red-700', bg: 'bg-red-50', ring: 'ring-red-200' },
  SUSPENDED: { label: 'Suspended', color: 'text-neutral-700', bg: 'bg-neutral-100', ring: 'ring-neutral-200' },
};

export const ROLES = {
  USER: 'USER',
  PHARMACY: 'PHARMACY',
  ADMIN: 'ADMIN',
};

export const OPERATING_DAYS = [
  { key: 'monday', label: 'Monday' },
  { key: 'tuesday', label: 'Tuesday' },
  { key: 'wednesday', label: 'Wednesday' },
  { key: 'thursday', label: 'Thursday' },
  { key: 'friday', label: 'Friday' },
  { key: 'saturday', label: 'Saturday' },
  { key: 'sunday', label: 'Sunday' },
];

export const CHART_COLORS = {
  available: '#16a34a',
  lowStock: '#ca8a04',
  outOfStock: '#dc2626',
  primary: '#059669',
  teal: '#0f766e',
  purple: '#7c3aed',
  orange: '#ea580c',
  pink: '#db2777',
};

export const CHART_PALETTE = [
  '#059669', '#0f766e', '#7c3aed', '#ea580c', '#db2877',
  '#16a34a', '#ca8a04', '#dc2626', '#0891b2', '#65a30d',
];
