// Comprehensive Real Medicine Database for MediFind
// 100+ commonly available medicines in India

export const MEDICINE_DATABASE = [
  // ── ANALGESICS / ANTIPYRETICS ──────────────────────────────────────────
  { id: 1, name: 'Paracetamol', genericName: 'Acetaminophen', brand: 'Crocin / Dolo', category: 'Analgesic / Antipyretic', manufacturer: 'GSK Pharmaceuticals', strength: '500mg', dosageForm: 'Tablet', price: 12, description: 'Relieves mild to moderate pain and reduces fever. Commonly used for headache, body ache, cold and flu.', sideEffects: 'Nausea, liver damage (overdose)', prescription: false, popular: true },
  { id: 2, name: 'Paracetamol', genericName: 'Acetaminophen', brand: 'Calpol', category: 'Analgesic / Antipyretic', manufacturer: 'Glaxo SmithKline', strength: '650mg', dosageForm: 'Tablet', price: 24, description: 'Higher strength paracetamol for adults with more severe pain or high fever.', sideEffects: 'Nausea, liver damage (overdose)', prescription: false, popular: true },
  { id: 3, name: 'Ibuprofen', genericName: 'Ibuprofen', brand: 'Brufen / Advil', category: 'NSAID / Anti-inflammatory', manufacturer: 'Abbott India', strength: '400mg', dosageForm: 'Tablet', price: 28, description: 'Anti-inflammatory, analgesic, and antipyretic. Used for pain, fever, and inflammatory conditions.', sideEffects: 'GI irritation, stomach ulcer, kidney issues', prescription: false, popular: true },
  { id: 4, name: 'Diclofenac Sodium', genericName: 'Diclofenac', brand: 'Voveran / Voltaren', category: 'NSAID / Anti-inflammatory', manufacturer: 'Novartis India', strength: '50mg', dosageForm: 'Tablet', price: 35, description: 'Nonsteroidal anti-inflammatory drug used for arthritis, muscle pain, and post-operative pain.', sideEffects: 'GI issues, cardiovascular risk', prescription: true, popular: false },
  { id: 5, name: 'Aspirin', genericName: 'Acetylsalicylic Acid', brand: 'Disprin / Ecosprin', category: 'Analgesic / Antipyretic', manufacturer: 'Bayer', strength: '75mg', dosageForm: 'Tablet', price: 18, description: 'Used for pain relief, fever reduction, and as a blood thinner to prevent heart attacks.', sideEffects: 'GI bleeding, Reye\'s syndrome in children', prescription: false, popular: true },
  { id: 6, name: 'Tramadol', genericName: 'Tramadol HCl', brand: 'Ultram / Tramazac', category: 'Opioid Analgesic', manufacturer: 'Sun Pharma', strength: '50mg', dosageForm: 'Capsule', price: 65, description: 'Opioid analgesic for moderate to moderately severe pain.', sideEffects: 'Dizziness, nausea, dependence risk', prescription: true, popular: false },

  // ── ANTIBIOTICS ────────────────────────────────────────────────────────
  { id: 7, name: 'Amoxicillin', genericName: 'Amoxicillin Trihydrate', brand: 'Mox / Amoxil', category: 'Antibiotic', manufacturer: 'Cipla Ltd.', strength: '500mg', dosageForm: 'Capsule', price: 85, description: 'Broad-spectrum penicillin antibiotic for bacterial infections including ear, throat, urinary tract.', sideEffects: 'Diarrhea, rash, allergic reactions', prescription: true, popular: true },
  { id: 8, name: 'Azithromycin', genericName: 'Azithromycin Dihydrate', brand: 'Zithromax / Azee', category: 'Antibiotic', manufacturer: 'Pfizer India', strength: '500mg', dosageForm: 'Tablet', price: 145, description: 'Macrolide antibiotic used for respiratory infections, skin infections, and STIs.', sideEffects: 'GI upset, cardiac arrhythmia (rare)', prescription: true, popular: true },
  { id: 9, name: 'Ciprofloxacin', genericName: 'Ciprofloxacin HCl', brand: 'Cifran / Ciplox', category: 'Antibiotic', manufacturer: 'Cipla Ltd.', strength: '500mg', dosageForm: 'Tablet', price: 95, description: 'Fluoroquinolone antibiotic for UTI, respiratory, and GI infections.', sideEffects: 'Tendon damage, photosensitivity', prescription: true, popular: false },
  { id: 10, name: 'Doxycycline', genericName: 'Doxycycline Hyclate', brand: 'Vibramycin / Doxt', category: 'Antibiotic', manufacturer: 'Pfizer India', strength: '100mg', dosageForm: 'Capsule', price: 75, description: 'Tetracycline antibiotic for acne, malaria prevention, and infections.', sideEffects: 'Photosensitivity, GI issues, tooth discoloration (children)', prescription: true, popular: false },
  { id: 11, name: 'Metronidazole', genericName: 'Metronidazole', brand: 'Flagyl / Metrogyl', category: 'Antibiotic', manufacturer: 'Abbott India', strength: '400mg', dosageForm: 'Tablet', price: 32, description: 'Antibiotic and antiprotozoal for anaerobic bacterial infections, amoebic dysentery.', sideEffects: 'Metallic taste, nausea, alcohol interaction', prescription: true, popular: true },
  { id: 12, name: 'Cephalexin', genericName: 'Cefalexin', brand: 'Keflex / Sporidex', category: 'Antibiotic', manufacturer: 'Ranbaxy', strength: '500mg', dosageForm: 'Capsule', price: 110, description: 'First-generation cephalosporin for skin, respiratory, and urinary tract infections.', sideEffects: 'Diarrhea, allergic reactions', prescription: true, popular: false },
  { id: 13, name: 'Clarithromycin', genericName: 'Clarithromycin', brand: 'Biaxin / Claribid', category: 'Antibiotic', manufacturer: 'Abbott India', strength: '500mg', dosageForm: 'Tablet', price: 165, description: 'Macrolide antibiotic for respiratory infections and H. pylori eradication.', sideEffects: 'GI upset, taste disturbances', prescription: true, popular: false },
  { id: 14, name: 'Amoxicillin + Clavulanate', genericName: 'Co-Amoxiclav', brand: 'Augmentin', category: 'Antibiotic', manufacturer: 'GSK India', strength: '625mg', dosageForm: 'Tablet', price: 185, description: 'Combination antibiotic resistant to beta-lactamase for severe bacterial infections.', sideEffects: 'Diarrhea, liver issues (rare)', prescription: true, popular: true },

  // ── ANTIHISTAMINES ────────────────────────────────────────────────────
  { id: 15, name: 'Cetirizine', genericName: 'Cetirizine HCl', brand: 'Zyrtec / Cetzine', category: 'Antihistamine', manufacturer: 'Sun Pharma', strength: '10mg', dosageForm: 'Tablet', price: 35, description: 'Second-generation antihistamine for allergy relief — hay fever, urticaria, allergic rhinitis.', sideEffects: 'Mild drowsiness, dry mouth', prescription: false, popular: true },
  { id: 16, name: 'Loratadine', genericName: 'Loratadine', brand: 'Claritin / Lorfast', category: 'Antihistamine', manufacturer: 'Cipla', strength: '10mg', dosageForm: 'Tablet', price: 42, description: 'Non-drowsy antihistamine for allergic rhinitis and urticaria.', sideEffects: 'Headache, dry mouth', prescription: false, popular: true },
  { id: 17, name: 'Fexofenadine', genericName: 'Fexofenadine HCl', brand: 'Allegra / Fexo', category: 'Antihistamine', manufacturer: 'Sanofi India', strength: '120mg', dosageForm: 'Tablet', price: 68, description: 'Non-sedating antihistamine for seasonal allergic rhinitis and chronic urticaria.', sideEffects: 'Headache, nausea', prescription: false, popular: false },
  { id: 18, name: 'Chlorpheniramine', genericName: 'Chlorphenamine Maleate', brand: 'CTM / Piriton', category: 'Antihistamine', manufacturer: 'GSK India', strength: '4mg', dosageForm: 'Tablet', price: 15, description: 'First-generation antihistamine for allergies, cold, and sleep aid.', sideEffects: 'Drowsiness, dry mouth, urinary retention', prescription: false, popular: false },
  { id: 19, name: 'Montelukast', genericName: 'Montelukast Sodium', brand: 'Singulair / Montair', category: 'Antihistamine', manufacturer: 'Cipla', strength: '10mg', dosageForm: 'Tablet', price: 120, description: 'Leukotriene receptor antagonist for asthma and allergic rhinitis prevention.', sideEffects: 'Headache, behavioral changes', prescription: true, popular: false },

  // ── ANTIDIABETICS ─────────────────────────────────────────────────────
  { id: 20, name: 'Metformin', genericName: 'Metformin HCl', brand: 'Glucophage / Glycomet', category: 'Antidiabetic', manufacturer: 'USV Ltd.', strength: '500mg', dosageForm: 'Tablet', price: 22, description: 'First-line medication for type 2 diabetes. Reduces glucose production in the liver.', sideEffects: 'GI upset, lactic acidosis (rare)', prescription: true, popular: true },
  { id: 21, name: 'Glimepiride', genericName: 'Glimepiride', brand: 'Amaryl / Glimpid', category: 'Antidiabetic', manufacturer: 'Sanofi India', strength: '2mg', dosageForm: 'Tablet', price: 55, description: 'Sulfonylurea antidiabetic for type 2 diabetes — stimulates insulin release.', sideEffects: 'Hypoglycemia, weight gain', prescription: true, popular: false },
  { id: 22, name: 'Glipizide', genericName: 'Glipizide', brand: 'Glucotrol / Dibizide', category: 'Antidiabetic', manufacturer: 'Pfizer', strength: '5mg', dosageForm: 'Tablet', price: 48, description: 'Sulfonylurea for type 2 diabetes management.', sideEffects: 'Hypoglycemia, nausea', prescription: true, popular: false },
  { id: 23, name: 'Sitagliptin', genericName: 'Sitagliptin Phosphate', brand: 'Januvia / Sitaday', category: 'Antidiabetic', manufacturer: 'MSD India', strength: '100mg', dosageForm: 'Tablet', price: 285, description: 'DPP-4 inhibitor for type 2 diabetes management.', sideEffects: 'Nasopharyngitis, pancreatitis (rare)', prescription: true, popular: false },
  { id: 24, name: 'Insulin Glargine', genericName: 'Insulin Glargine', brand: 'Lantus / Basalog', category: 'Antidiabetic', manufacturer: 'Sanofi India', strength: '100IU/ml', dosageForm: 'Injection', price: 850, description: 'Long-acting insulin analog for type 1 and type 2 diabetes.', sideEffects: 'Hypoglycemia, injection site reactions', prescription: true, popular: false },

  // ── ANTIHYPERTENSIVES ─────────────────────────────────────────────────
  { id: 25, name: 'Amlodipine', genericName: 'Amlodipine Besylate', brand: 'Norvasc / Amlip', category: 'Antihypertensive', manufacturer: 'Pfizer India', strength: '5mg', dosageForm: 'Tablet', price: 38, description: 'Calcium channel blocker for hypertension and angina.', sideEffects: 'Ankle swelling, flushing, palpitations', prescription: true, popular: true },
  { id: 26, name: 'Atenolol', genericName: 'Atenolol', brand: 'Tenormin / Aten', category: 'Antihypertensive', manufacturer: 'AstraZeneca', strength: '50mg', dosageForm: 'Tablet', price: 28, description: 'Beta-blocker for hypertension and heart conditions.', sideEffects: 'Fatigue, cold extremities, bradycardia', prescription: true, popular: true },
  { id: 27, name: 'Losartan', genericName: 'Losartan Potassium', brand: 'Cozaar / Losacar', category: 'Antihypertensive', manufacturer: 'MSD India', strength: '50mg', dosageForm: 'Tablet', price: 65, description: 'Angiotensin receptor blocker (ARB) for hypertension and kidney protection in diabetics.', sideEffects: 'Dizziness, hyperkalemia', prescription: true, popular: false },
  { id: 28, name: 'Telmisartan', genericName: 'Telmisartan', brand: 'Micardis / Telma', category: 'Antihypertensive', manufacturer: 'Boehringer Ingelheim', strength: '40mg', dosageForm: 'Tablet', price: 72, description: 'ARB for hypertension with 24-hour blood pressure control.', sideEffects: 'Back pain, sinusitis', prescription: true, popular: false },
  { id: 29, name: 'Enalapril', genericName: 'Enalapril Maleate', brand: 'Vasotec / Envas', category: 'Antihypertensive', manufacturer: 'MSD India', strength: '5mg', dosageForm: 'Tablet', price: 42, description: 'ACE inhibitor for hypertension and heart failure.', sideEffects: 'Dry cough, dizziness, hyperkalemia', prescription: true, popular: false },
  { id: 30, name: 'Ramipril', genericName: 'Ramipril', brand: 'Altace / Cardace', category: 'Antihypertensive', manufacturer: 'Sanofi India', strength: '5mg', dosageForm: 'Capsule', price: 55, description: 'ACE inhibitor for hypertension and post-MI heart protection.', sideEffects: 'Cough, dizziness, angioedema (rare)', prescription: true, popular: false },

  // ── CARDIOVASCULAR ────────────────────────────────────────────────────
  { id: 31, name: 'Atorvastatin', genericName: 'Atorvastatin Calcium', brand: 'Lipitor / Atorva', category: 'Cardiovascular', manufacturer: 'Pfizer India', strength: '10mg', dosageForm: 'Tablet', price: 45, description: 'Statin for lowering LDL cholesterol and preventing cardiovascular events.', sideEffects: 'Muscle pain, liver enzyme elevation', prescription: true, popular: true },
  { id: 32, name: 'Rosuvastatin', genericName: 'Rosuvastatin Calcium', brand: 'Crestor / Rosuvas', category: 'Cardiovascular', manufacturer: 'AstraZeneca', strength: '10mg', dosageForm: 'Tablet', price: 68, description: 'High-potency statin for cholesterol management.', sideEffects: 'Muscle pain, headache', prescription: true, popular: true },
  { id: 33, name: 'Clopidogrel', genericName: 'Clopidogrel Bisulfate', brand: 'Plavix / Clopilet', category: 'Cardiovascular', manufacturer: 'Sanofi India', strength: '75mg', dosageForm: 'Tablet', price: 88, description: 'Antiplatelet agent to prevent blood clots in heart disease patients.', sideEffects: 'Bleeding risk, bruising', prescription: true, popular: false },
  { id: 34, name: 'Digoxin', genericName: 'Digoxin', brand: 'Lanoxin / Lanoxicaps', category: 'Cardiovascular', manufacturer: 'GSK India', strength: '0.25mg', dosageForm: 'Tablet', price: 38, description: 'Cardiac glycoside for heart failure and atrial fibrillation.', sideEffects: 'Nausea, arrhythmias, narrow therapeutic index', prescription: true, popular: false },

  // ── ANTACIDS / GI ─────────────────────────────────────────────────────
  { id: 35, name: 'Omeprazole', genericName: 'Omeprazole', brand: 'Prilosec / Omez', category: 'Antacid / GI', manufacturer: 'Dr Reddy\'s', strength: '20mg', dosageForm: 'Capsule', price: 52, description: 'Proton pump inhibitor for GERD, peptic ulcer, and acid reflux.', sideEffects: 'Headache, diarrhea, B12 deficiency (long-term)', prescription: false, popular: true },
  { id: 36, name: 'Pantoprazole', genericName: 'Pantoprazole Sodium', brand: 'Protonix / Pan', category: 'Antacid / GI', manufacturer: 'Sun Pharma', strength: '40mg', dosageForm: 'Tablet', price: 48, description: 'PPI for GERD, erosive esophagitis, and Zollinger-Ellison syndrome.', sideEffects: 'Headache, diarrhea, magnesium deficiency', prescription: false, popular: true },
  { id: 37, name: 'Ranitidine', genericName: 'Ranitidine HCl', brand: 'Zantac / Rantac', category: 'Antacid / GI', manufacturer: 'GSK India', strength: '150mg', dosageForm: 'Tablet', price: 28, description: 'H2-blocker for peptic ulcers and GERD.', sideEffects: 'Headache, constipation', prescription: false, popular: false },
  { id: 38, name: 'Domperidone', genericName: 'Domperidone', brand: 'Motilium / Domstal', category: 'Antacid / GI', manufacturer: 'Janssen India', strength: '10mg', dosageForm: 'Tablet', price: 32, description: 'Prokinetic agent for nausea, vomiting, and gastroparesis.', sideEffects: 'Headache, cardiac arrhythmia (high dose)', prescription: false, popular: true },
  { id: 39, name: 'Ondansetron', genericName: 'Ondansetron HCl', brand: 'Zofran / Emeset', category: 'Antacid / GI', manufacturer: 'GSK India', strength: '4mg', dosageForm: 'Tablet', price: 68, description: '5-HT3 antagonist for chemotherapy-induced and post-operative nausea.', sideEffects: 'Constipation, headache, QT prolongation', prescription: true, popular: false },
  { id: 40, name: 'Loperamide', genericName: 'Loperamide HCl', brand: 'Imodium / Lopamide', category: 'Antacid / GI', manufacturer: 'Janssen India', strength: '2mg', dosageForm: 'Capsule', price: 38, description: 'Antidiarrheal agent for acute and chronic diarrhea.', sideEffects: 'Constipation, abdominal cramps', prescription: false, popular: true },
  { id: 41, name: 'Lactulose', genericName: 'Lactulose', brand: 'Duphalac / Looz', category: 'Antacid / GI', manufacturer: 'Abbott India', strength: '10g/15ml', dosageForm: 'Syrup', price: 95, description: 'Osmotic laxative for constipation and hepatic encephalopathy.', sideEffects: 'Bloating, flatulence, diarrhea', prescription: false, popular: false },

  // ── RESPIRATORY ───────────────────────────────────────────────────────
  { id: 42, name: 'Salbutamol', genericName: 'Albuterol', brand: 'Ventolin / Asthalin', category: 'Respiratory', manufacturer: 'GSK India', strength: '100mcg/dose', dosageForm: 'Inhaler', price: 165, description: 'Short-acting bronchodilator for asthma and COPD relief.', sideEffects: 'Tremor, palpitations, headache', prescription: true, popular: true },
  { id: 43, name: 'Budesonide', genericName: 'Budesonide', brand: 'Pulmicort / Budecort', category: 'Respiratory', manufacturer: 'AstraZeneca', strength: '200mcg/dose', dosageForm: 'Inhaler', price: 285, description: 'Inhaled corticosteroid for asthma and COPD management.', sideEffects: 'Oral thrush, dysphonia', prescription: true, popular: false },
  { id: 44, name: 'Theophylline', genericName: 'Theophylline', brand: 'Theo-24 / Deriphyllin', category: 'Respiratory', manufacturer: 'Cipla', strength: '200mg', dosageForm: 'Tablet', price: 45, description: 'Bronchodilator for asthma and COPD.', sideEffects: 'Nausea, insomnia, arrhythmia (toxicity)', prescription: true, popular: false },
  { id: 45, name: 'Dextromethorphan', genericName: 'Dextromethorphan HBr', brand: 'Benylin / Delsym', category: 'Respiratory', manufacturer: 'Johnson & Johnson', strength: '15mg/5ml', dosageForm: 'Syrup', price: 78, description: 'Antitussive (cough suppressant) for dry cough.', sideEffects: 'Dizziness, drowsiness', prescription: false, popular: true },
  { id: 46, name: 'Guaifenesin', genericName: 'Guaifenesin', brand: 'Mucinex / Alex', category: 'Respiratory', manufacturer: 'Reckitt', strength: '200mg/5ml', dosageForm: 'Syrup', price: 65, description: 'Expectorant that thins and loosens mucus for productive cough.', sideEffects: 'Nausea, vomiting', prescription: false, popular: true },

  // ── NEUROLOGICAL / CNS ────────────────────────────────────────────────
  { id: 47, name: 'Amitriptyline', genericName: 'Amitriptyline HCl', brand: 'Elavil / Tryptomer', category: 'Neurological', manufacturer: 'Sun Pharma', strength: '25mg', dosageForm: 'Tablet', price: 38, description: 'Tricyclic antidepressant for depression and neuropathic pain.', sideEffects: 'Dry mouth, sedation, cardiac effects', prescription: true, popular: false },
  { id: 48, name: 'Sertraline', genericName: 'Sertraline HCl', brand: 'Zoloft / Serta', category: 'Neurological', manufacturer: 'Pfizer India', strength: '50mg', dosageForm: 'Tablet', price: 95, description: 'SSRI antidepressant for depression, OCD, and anxiety disorders.', sideEffects: 'Nausea, insomnia, sexual dysfunction', prescription: true, popular: false },
  { id: 49, name: 'Alprazolam', genericName: 'Alprazolam', brand: 'Xanax / Alprax', category: 'Neurological', manufacturer: 'Pfizer India', strength: '0.25mg', dosageForm: 'Tablet', price: 28, description: 'Benzodiazepine for anxiety disorders and panic attacks.', sideEffects: 'Sedation, dependence, withdrawal', prescription: true, popular: false },
  { id: 50, name: 'Phenytoin', genericName: 'Phenytoin Sodium', brand: 'Dilantin / Eptoin', category: 'Neurological', manufacturer: 'Abbott India', strength: '100mg', dosageForm: 'Tablet', price: 52, description: 'Antiepileptic for seizure control.', sideEffects: 'Gingival hyperplasia, ataxia, teratogenicity', prescription: true, popular: false },
  { id: 51, name: 'Levodopa + Carbidopa', genericName: 'Levodopa/Carbidopa', brand: 'Sinemet / Syndopa', category: 'Neurological', manufacturer: 'MSD India', strength: '100mg/25mg', dosageForm: 'Tablet', price: 125, description: 'Dopaminergic therapy for Parkinson\'s disease.', sideEffects: 'Dyskinesias, nausea, hallucinations', prescription: true, popular: false },
  { id: 52, name: 'Gabapentin', genericName: 'Gabapentin', brand: 'Neurontin / Gabapin', category: 'Neurological', manufacturer: 'Pfizer India', strength: '300mg', dosageForm: 'Capsule', price: 75, description: 'Anticonvulsant and neuropathic pain agent.', sideEffects: 'Dizziness, somnolence, ataxia', prescription: true, popular: false },

  // ── DERMATOLOGICAL ────────────────────────────────────────────────────
  { id: 53, name: 'Betamethasone Cream', genericName: 'Betamethasone Valerate', brand: 'Betnovate / Beta-N', category: 'Dermatological', manufacturer: 'GSK India', strength: '0.1%', dosageForm: 'Cream', price: 55, description: 'Topical corticosteroid for eczema, psoriasis, and allergic skin conditions.', sideEffects: 'Skin thinning, stretch marks (prolonged use)', prescription: true, popular: true },
  { id: 54, name: 'Clotrimazole Cream', genericName: 'Clotrimazole', brand: 'Canesten / Clof', category: 'Dermatological', manufacturer: 'Bayer', strength: '1%', dosageForm: 'Cream', price: 45, description: 'Antifungal for ringworm, athlete\'s foot, and candidiasis.', sideEffects: 'Mild burning, irritation', prescription: false, popular: true },
  { id: 55, name: 'Tretinoin Cream', genericName: 'Tretinoin', brand: 'Retin-A / Retino-A', category: 'Dermatological', manufacturer: 'Johnson & Johnson', strength: '0.025%', dosageForm: 'Cream', price: 165, description: 'Retinoid for acne treatment and anti-aging.', sideEffects: 'Skin dryness, photosensitivity', prescription: true, popular: false },
  { id: 56, name: 'Hydrocortisone Cream', genericName: 'Hydrocortisone', brand: 'Cortaid / HC Cream', category: 'Dermatological', manufacturer: 'Cipla', strength: '1%', dosageForm: 'Cream', price: 35, description: 'Mild topical corticosteroid for skin itching and inflammation.', sideEffects: 'Skin thinning (prolonged use)', prescription: false, popular: false },
  { id: 57, name: 'Mupirocin Ointment', genericName: 'Mupirocin', brand: 'Bactroban / Mupiderm', category: 'Dermatological', manufacturer: 'GSK India', strength: '2%', dosageForm: 'Ointment', price: 120, description: 'Topical antibiotic for impetigo and skin infections.', sideEffects: 'Burning, stinging', prescription: true, popular: false },

  // ── VITAMINS / SUPPLEMENTS ────────────────────────────────────────────
  { id: 58, name: 'Vitamin C', genericName: 'Ascorbic Acid', brand: 'Celin / Limcee', category: 'Vitamin / Supplement', manufacturer: 'Abbott India', strength: '500mg', dosageForm: 'Tablet', price: 25, description: 'Vitamin C supplement for immunity and antioxidant support.', sideEffects: 'Kidney stones (high dose), GI upset', prescription: false, popular: true },
  { id: 59, name: 'Vitamin D3', genericName: 'Cholecalciferol', brand: 'Calcirol / Uprise D3', category: 'Vitamin / Supplement', manufacturer: 'Intas Pharmaceuticals', strength: '60000 IU', dosageForm: 'Capsule', price: 38, description: 'Vitamin D3 for bone health, immunity, and deficiency treatment.', sideEffects: 'Hypercalcemia (overdose)', prescription: false, popular: true },
  { id: 60, name: 'Vitamin B12', genericName: 'Cyanocobalamin', brand: 'Neurobion / Cobadex', category: 'Vitamin / Supplement', manufacturer: 'Merck India', strength: '500mcg', dosageForm: 'Tablet', price: 42, description: 'Vitamin B12 supplement for nerve health and anemia.', sideEffects: 'Rare — acne, allergic reactions', prescription: false, popular: true },
  { id: 61, name: 'Iron + Folic Acid', genericName: 'Ferrous Sulfate + Folic Acid', brand: 'Feronia / Orofer XT', category: 'Vitamin / Supplement', manufacturer: 'Emcure Pharmaceuticals', strength: '150mg + 1.5mg', dosageForm: 'Tablet', price: 48, description: 'Iron and folic acid supplement for anemia and pregnancy.', sideEffects: 'Constipation, dark stools, GI upset', prescription: false, popular: true },
  { id: 62, name: 'Calcium + Vitamin D', genericName: 'Calcium Carbonate + D3', brand: 'Calcimax / Shelcal', category: 'Vitamin / Supplement', manufacturer: 'Elder Pharmaceuticals', strength: '500mg + 250IU', dosageForm: 'Tablet', price: 65, description: 'Calcium supplement for bone health.', sideEffects: 'Constipation, hypercalcemia (overdose)', prescription: false, popular: true },
  { id: 63, name: 'Omega-3 Fish Oil', genericName: 'Omega-3 Fatty Acids', brand: 'Seacod / Omacor', category: 'Vitamin / Supplement', manufacturer: 'Merck India', strength: '1000mg', dosageForm: 'Capsule', price: 85, description: 'Omega-3 supplement for cardiovascular health and brain function.', sideEffects: 'Fishy aftertaste, GI upset', prescription: false, popular: false },
  { id: 64, name: 'Zinc', genericName: 'Zinc Sulfate', brand: 'Zincovit / Zinconia', category: 'Vitamin / Supplement', manufacturer: 'Apex Laboratories', strength: '50mg', dosageForm: 'Tablet', price: 28, description: 'Zinc supplement for immunity, wound healing, and growth.', sideEffects: 'Nausea, metallic taste (high dose)', prescription: false, popular: false },

  // ── ANTIFUNGALS ───────────────────────────────────────────────────────
  { id: 65, name: 'Fluconazole', genericName: 'Fluconazole', brand: 'Diflucan / Forcan', category: 'Antifungal', manufacturer: 'Pfizer India', strength: '150mg', dosageForm: 'Capsule', price: 45, description: 'Systemic antifungal for candidiasis and cryptococcal infections.', sideEffects: 'GI upset, liver enzyme elevation', prescription: true, popular: true },
  { id: 66, name: 'Itraconazole', genericName: 'Itraconazole', brand: 'Sporanox / Canditral', category: 'Antifungal', manufacturer: 'Janssen India', strength: '100mg', dosageForm: 'Capsule', price: 185, description: 'Broad-spectrum antifungal for systemic fungal infections.', sideEffects: 'GI upset, liver toxicity, heart failure risk', prescription: true, popular: false },
  { id: 67, name: 'Terbinafine', genericName: 'Terbinafine HCl', brand: 'Lamisil / Terbicip', category: 'Antifungal', manufacturer: 'Novartis India', strength: '250mg', dosageForm: 'Tablet', price: 135, description: 'Antifungal for onychomycosis (nail fungal infections) and tinea.', sideEffects: 'GI upset, liver enzyme elevation, taste disturbances', prescription: true, popular: false },

  // ── ANTIVIRALS ────────────────────────────────────────────────────────
  { id: 68, name: 'Acyclovir', genericName: 'Acyclovir', brand: 'Zovirax / Acivir', category: 'Antiviral', manufacturer: 'Cipla', strength: '400mg', dosageForm: 'Tablet', price: 85, description: 'Antiviral for herpes simplex, herpes zoster, and varicella-zoster infections.', sideEffects: 'Nausea, headache, kidney dysfunction (IV)', prescription: true, popular: false },
  { id: 69, name: 'Oseltamivir', genericName: 'Oseltamivir Phosphate', brand: 'Tamiflu / Antiflu', category: 'Antiviral', manufacturer: 'Roche India', strength: '75mg', dosageForm: 'Capsule', price: 320, description: 'Neuraminidase inhibitor for influenza A and B treatment and prevention.', sideEffects: 'Nausea, vomiting', prescription: true, popular: false },

  // ── THYROID ───────────────────────────────────────────────────────────
  { id: 70, name: 'Levothyroxine', genericName: 'Levothyroxine Sodium', brand: 'Synthroid / Thyronorm', category: 'Thyroid', manufacturer: 'Abbott India', strength: '50mcg', dosageForm: 'Tablet', price: 32, description: 'Synthetic thyroid hormone for hypothyroidism treatment.', sideEffects: 'Palpitations, weight loss, insomnia (overdose)', prescription: true, popular: true },
  { id: 71, name: 'Methimazole', genericName: 'Thiamazole', brand: 'Tapazole / Thyrozol', category: 'Thyroid', manufacturer: 'Merck India', strength: '5mg', dosageForm: 'Tablet', price: 48, description: 'Antithyroid drug for hyperthyroidism treatment.', sideEffects: 'Agranulocytosis (rare), rash', prescription: true, popular: false },

  // ── OPHTHALMIC ────────────────────────────────────────────────────────
  { id: 72, name: 'Ciprofloxacin Eye Drops', genericName: 'Ciprofloxacin HCl', brand: 'Ciloxan / Ciplox Eye', category: 'Ophthalmic', manufacturer: 'Cipla', strength: '0.3%', dosageForm: 'Drops', price: 55, description: 'Antibiotic eye drops for bacterial conjunctivitis.', sideEffects: 'Burning, stinging, white crystalline precipitate', prescription: true, popular: true },
  { id: 73, name: 'Timolol Eye Drops', genericName: 'Timolol Maleate', brand: 'Timoptic / Ocupres', category: 'Ophthalmic', manufacturer: 'MSD India', strength: '0.5%', dosageForm: 'Drops', price: 78, description: 'Beta-blocker eye drops for glaucoma and ocular hypertension.', sideEffects: 'Bradycardia, bronchospasm (systemic absorption)', prescription: true, popular: false },
  { id: 74, name: 'Artificial Tears', genericName: 'Carboxymethylcellulose', brand: 'Refresh / Systane', category: 'Ophthalmic', manufacturer: 'Allergan India', strength: '0.5%', dosageForm: 'Drops', price: 145, description: 'Lubricating eye drops for dry eye relief.', sideEffects: 'Mild blurring (temporary)', prescription: false, popular: true },

  // ── HORMONES ──────────────────────────────────────────────────────────
  { id: 75, name: 'Prednisolone', genericName: 'Prednisolone', brand: 'Prelone / Wysolone', category: 'Corticosteroid', manufacturer: 'Pfizer India', strength: '5mg', dosageForm: 'Tablet', price: 22, description: 'Corticosteroid for inflammation, autoimmune diseases, and allergies.', sideEffects: 'Weight gain, osteoporosis, hyperglycemia', prescription: true, popular: true },
  { id: 76, name: 'Dexamethasone', genericName: 'Dexamethasone', brand: 'Decadron / Dexona', category: 'Corticosteroid', manufacturer: 'Abbott India', strength: '0.5mg', dosageForm: 'Tablet', price: 18, description: 'Potent corticosteroid for severe inflammation and cerebral edema.', sideEffects: 'Cushing\'s syndrome (long-term), infections', prescription: true, popular: false },
  { id: 77, name: 'Oral Contraceptive Pill', genericName: 'Ethinyl Estradiol + Levonorgestrel', brand: 'Ovral-L / Mala-N', category: 'Hormones', manufacturer: 'Wyeth India', strength: '30mcg + 0.15mg', dosageForm: 'Tablet', price: 48, description: 'Combined oral contraceptive for birth control.', sideEffects: 'Nausea, breakthrough bleeding, thrombosis (rare)', prescription: true, popular: false },

  // ── UROLOGICAL ────────────────────────────────────────────────────────
  { id: 78, name: 'Tamsulosin', genericName: 'Tamsulosin HCl', brand: 'Flomax / Urimax', category: 'Urological', manufacturer: 'Ranbaxy', strength: '0.4mg', dosageForm: 'Capsule', price: 68, description: 'Alpha-blocker for benign prostatic hyperplasia.', sideEffects: 'Dizziness, retrograde ejaculation', prescription: true, popular: false },
  { id: 79, name: 'Sildenafil', genericName: 'Sildenafil Citrate', brand: 'Viagra / Penegra', category: 'Urological', manufacturer: 'Pfizer India', strength: '50mg', dosageForm: 'Tablet', price: 225, description: 'PDE5 inhibitor for erectile dysfunction and pulmonary hypertension.', sideEffects: 'Flushing, headache, visual changes', prescription: true, popular: false },

  // ── ANTIMALARIALS ─────────────────────────────────────────────────────
  { id: 80, name: 'Chloroquine', genericName: 'Chloroquine Phosphate', brand: 'Aralen / Lariago', category: 'Antimalarial', manufacturer: 'Ipca Laboratories', strength: '250mg', dosageForm: 'Tablet', price: 28, description: 'Antimalarial drug for treatment and prevention of malaria.', sideEffects: 'GI upset, vision problems (long-term)', prescription: true, popular: false },
  { id: 81, name: 'Artemether + Lumefantrine', genericName: 'Artemether/Lumefantrine', brand: 'Coartem / Lumartem', category: 'Antimalarial', manufacturer: 'Novartis India', strength: '20mg/120mg', dosageForm: 'Tablet', price: 165, description: 'Combination antimalarial for uncomplicated falciparum malaria.', sideEffects: 'Headache, dizziness, QT prolongation', prescription: true, popular: false },

  // ── PEDIATRIC ─────────────────────────────────────────────────────────
  { id: 82, name: 'Paracetamol Syrup', genericName: 'Acetaminophen', brand: 'Calpol Syrup / Metacin', category: 'Analgesic / Antipyretic', manufacturer: 'GSK India', strength: '125mg/5ml', dosageForm: 'Syrup', price: 42, description: 'Paracetamol syrup for fever and mild pain in children.', sideEffects: 'Liver damage (overdose)', prescription: false, popular: true },
  { id: 83, name: 'Amoxicillin Dry Syrup', genericName: 'Amoxicillin Trihydrate', brand: 'Mox / Novamox', category: 'Antibiotic', manufacturer: 'Cipla Ltd.', strength: '125mg/5ml', dosageForm: 'Syrup', price: 65, description: 'Amoxicillin oral suspension for bacterial infections in children.', sideEffects: 'Diarrhea, rash', prescription: true, popular: true },
  { id: 84, name: 'Cetirizine Syrup', genericName: 'Cetirizine HCl', brand: 'Cetzine Syrup / Zyncet', category: 'Antihistamine', manufacturer: 'Sun Pharma', strength: '5mg/5ml', dosageForm: 'Syrup', price: 48, description: 'Antihistamine syrup for allergy relief in children.', sideEffects: 'Mild drowsiness', prescription: false, popular: false },
  { id: 85, name: 'ORS Sachets', genericName: 'Oral Rehydration Salts', brand: 'Electral / ORS Powder', category: 'Electrolyte', manufacturer: 'Franco Indian Pharmaceuticals', strength: 'WHO formula', dosageForm: 'Powder', price: 12, description: 'Oral rehydration solution for diarrhea and dehydration in all ages.', sideEffects: 'Hypernatremia (excess intake)', prescription: false, popular: true },

  // ── INJECTABLE ────────────────────────────────────────────────────────
  { id: 86, name: 'Diclofenac Injection', genericName: 'Diclofenac Sodium', brand: 'Voveran Inj / Voltaflam', category: 'NSAID / Anti-inflammatory', manufacturer: 'Novartis India', strength: '75mg/3ml', dosageForm: 'Injection', price: 35, description: 'Injectable NSAID for acute pain management.', sideEffects: 'Injection site pain, GI effects', prescription: true, popular: false },
  { id: 87, name: 'Ondansetron Injection', genericName: 'Ondansetron HCl', brand: 'Zofran Inj / Emeset Inj', category: 'Antacid / GI', manufacturer: 'GSK India', strength: '4mg/2ml', dosageForm: 'Injection', price: 55, description: 'IV/IM antiemetic for severe nausea and vomiting.', sideEffects: 'Headache, QT prolongation', prescription: true, popular: false },

  // ── MISCELLANEOUS ─────────────────────────────────────────────────────
  { id: 88, name: 'Pantoprazole + Domperidone', genericName: 'Pantoprazole + Domperidone', brand: 'Pantop-D / Pan-D', category: 'Antacid / GI', manufacturer: 'Aristo Pharmaceuticals', strength: '40mg + 10mg', dosageForm: 'Capsule', price: 65, description: 'Combination for GERD with nausea and dysmotility.', sideEffects: 'Headache, diarrhea, cardiac arrhythmia', prescription: false, popular: true },
  { id: 89, name: 'Rabeprazole', genericName: 'Rabeprazole Sodium', brand: 'Aciphex / Razo', category: 'Antacid / GI', manufacturer: 'Eisai Pharmaceuticals', strength: '20mg', dosageForm: 'Tablet', price: 58, description: 'PPI for peptic ulcer, GERD, and H. pylori eradication.', sideEffects: 'Headache, diarrhea', prescription: false, popular: false },
  { id: 90, name: 'Spironolactone', genericName: 'Spironolactone', brand: 'Aldactone / Aldactide', category: 'Cardiovascular', manufacturer: 'Pfizer India', strength: '25mg', dosageForm: 'Tablet', price: 42, description: 'Potassium-sparing diuretic for hypertension and heart failure.', sideEffects: 'Gynecomastia, hyperkalemia', prescription: true, popular: false },
  { id: 91, name: 'Furosemide', genericName: 'Furosemide', brand: 'Lasix / Frusemide', category: 'Cardiovascular', manufacturer: 'Sanofi India', strength: '40mg', dosageForm: 'Tablet', price: 18, description: 'Loop diuretic for edema and hypertension.', sideEffects: 'Electrolyte imbalance, dehydration, ototoxicity', prescription: true, popular: false },
  { id: 92, name: 'Warfarin', genericName: 'Warfarin Sodium', brand: 'Coumadin / Warf', category: 'Cardiovascular', manufacturer: 'Unichem', strength: '5mg', dosageForm: 'Tablet', price: 45, description: 'Anticoagulant for thrombosis prevention, atrial fibrillation, and prosthetic heart valves.', sideEffects: 'Bleeding, requires INR monitoring', prescription: true, popular: false },
  { id: 93, name: 'Clonazepam', genericName: 'Clonazepam', brand: 'Klonopin / Clonotril', category: 'Neurological', manufacturer: 'Sun Pharma', strength: '0.5mg', dosageForm: 'Tablet', price: 32, description: 'Benzodiazepine for seizure disorders and panic disorder.', sideEffects: 'Sedation, dependence, withdrawal', prescription: true, popular: false },
  { id: 94, name: 'Multivitamin Tablets', genericName: 'Multivitamin + Multimineral', brand: 'Supradyn / A to Z', category: 'Vitamin / Supplement', manufacturer: 'Bayer', strength: 'Complete Formula', dosageForm: 'Tablet', price: 185, description: 'Comprehensive multivitamin for overall health and nutritional gaps.', sideEffects: 'Rare — nausea if taken on empty stomach', prescription: false, popular: true },
  { id: 95, name: 'Probiotics', genericName: 'Lactobacillus rhamnosus GG', brand: 'Enterogermina / Darolac', category: 'Antacid / GI', manufacturer: 'Sanofi India', strength: '2 billion CFU', dosageForm: 'Capsule', price: 125, description: 'Probiotic for gut health, diarrhea prevention, and antibiotic-associated diarrhea.', sideEffects: 'Bloating (transient)', prescription: false, popular: true },
  { id: 96, name: 'Diazepam', genericName: 'Diazepam', brand: 'Valium / Calmpose', category: 'Neurological', manufacturer: 'Roche India', strength: '5mg', dosageForm: 'Tablet', price: 22, description: 'Benzodiazepine for anxiety, seizures, and muscle spasm.', sideEffects: 'Sedation, dependence, respiratory depression', prescription: true, popular: false },
  { id: 97, name: 'Pantoprazole Injection', genericName: 'Pantoprazole Sodium', brand: 'Pantocid Inj / Pan Inj', category: 'Antacid / GI', manufacturer: 'Sun Pharma', strength: '40mg', dosageForm: 'Injection', price: 48, description: 'IV PPI for severe GERD and GI bleeds.', sideEffects: 'Headache, injection site pain', prescription: true, popular: false },
  { id: 98, name: 'Cefixime', genericName: 'Cefixime', brand: 'Suprax / Taxim-O', category: 'Antibiotic', manufacturer: 'Abbott India', strength: '200mg', dosageForm: 'Tablet', price: 125, description: 'Third-generation cephalosporin for respiratory, urinary, and ENT infections.', sideEffects: 'Diarrhea, GI disturbances', prescription: true, popular: true },
  { id: 99, name: 'Levocetirizine', genericName: 'Levocetirizine HCl', brand: 'Xyzal / L-Cet', category: 'Antihistamine', manufacturer: 'UCB India', strength: '5mg', dosageForm: 'Tablet', price: 42, description: 'Potent second-generation antihistamine for allergy relief.', sideEffects: 'Drowsiness, dry mouth', prescription: false, popular: true },
  { id: 100, name: 'Hydroxychloroquine', genericName: 'Hydroxychloroquine Sulfate', brand: 'Plaquenil / Hcqs', category: 'Antimalarial', manufacturer: 'Ipca Laboratories', strength: '200mg', dosageForm: 'Tablet', price: 95, description: 'Antimalarial also used for rheumatoid arthritis and lupus.', sideEffects: 'Retinopathy (long-term), GI upset', prescription: true, popular: false },
  { id: 101, name: 'Pantoprazole + Ondansetron', genericName: 'Pantoprazole + Ondansetron', brand: 'Pan-OD / Nexpro-OD', category: 'Antacid / GI', manufacturer: 'Intas Pharmaceuticals', strength: '40mg + 4mg', dosageForm: 'Tablet', price: 75, description: 'Combination for acid reflux with nausea during pregnancy or chemotherapy.', sideEffects: 'Headache, constipation', prescription: true, popular: false },
  { id: 102, name: 'Metoprolol', genericName: 'Metoprolol Succinate', brand: 'Lopressor / Met XL', category: 'Cardiovascular', manufacturer: 'AstraZeneca', strength: '25mg', dosageForm: 'Tablet', price: 45, description: 'Cardioselective beta-blocker for hypertension and heart failure.', sideEffects: 'Fatigue, bradycardia, cold extremities', prescription: true, popular: true },
  { id: 103, name: 'Esomeprazole', genericName: 'Esomeprazole Magnesium', brand: 'Nexium / Nexpro', category: 'Antacid / GI', manufacturer: 'AstraZeneca', strength: '40mg', dosageForm: 'Capsule', price: 78, description: 'S-isomer of omeprazole, PPI for GERD and erosive esophagitis.', sideEffects: 'Headache, diarrhea', prescription: false, popular: true },
  { id: 104, name: 'Bisoprolol', genericName: 'Bisoprolol Fumarate', brand: 'Zebeta / Biselect', category: 'Cardiovascular', manufacturer: 'Merck India', strength: '5mg', dosageForm: 'Tablet', price: 55, description: 'Cardioselective beta-blocker for hypertension and angina.', sideEffects: 'Fatigue, bradycardia', prescription: true, popular: false },
  { id: 105, name: 'Pregabalin', genericName: 'Pregabalin', brand: 'Lyrica / Pregabalin', category: 'Neurological', manufacturer: 'Pfizer India', strength: '75mg', dosageForm: 'Capsule', price: 95, description: 'Anticonvulsant for neuropathic pain, fibromyalgia, and anxiety.', sideEffects: 'Dizziness, somnolence, weight gain', prescription: true, popular: true },
];

// Helper to get all unique categories
export const ALL_CATEGORIES = [...new Set(MEDICINE_DATABASE.map(m => m.category))].sort();

// Helper to search medicines
export const searchMedicines = (query, category = '', limit = 20) => {
  const q = query?.toLowerCase().trim() || '';
  return MEDICINE_DATABASE
    .filter(m => {
      const matchesQuery = !q ||
        m.name.toLowerCase().includes(q) ||
        m.genericName.toLowerCase().includes(q) ||
        m.brand?.toLowerCase().includes(q) ||
        m.category.toLowerCase().includes(q) ||
        m.manufacturer.toLowerCase().includes(q);
      const matchesCategory = !category || m.category === category;
      return matchesQuery && matchesCategory;
    })
    .slice(0, limit);
};

// Helper to get popular medicines
export const getPopularMedicines = (limit = 12) =>
  MEDICINE_DATABASE.filter(m => m.popular).slice(0, limit);

// Helper to get medicine by id
export const getMedicineById = (id) =>
  MEDICINE_DATABASE.find(m => m.id === Number(id));

export default MEDICINE_DATABASE;
